React router dom
grabsks/uLift pull request #15
Opened 2020-03-12 00:22 UTC by luanfonsecap

2020-03-12 00:58 UTC, grabsks requested changes

2020-03-12 00:58 UTC, GrabK5 commented on ulift-web/src/index.js
> +import Routes from "./routes";
adicionar espaço

2020-03-13 00:11 UTC, grabsks approved these changes

2020-03-13 02:37 UTC, GuilhermehChaves approved these changes

2020-03-13 02:38 UTC, merged