estrutura base
grabsks/uLift pull request #2
Opened 2020-03-07 20:10 UTC by luanfonsecap

2020-03-08 13:38 UTC, GuilhermehChaves requested changes
Em App.js retornar apenas `<div> Hello world </div>`

2020-03-08 13:38 UTC, GuilhermehChaves commented on ulift-web/src/index.js
> +import * as serviceWorker from './serviceWorker';
Remover linha

2020-03-08 13:38 UTC, GuilhermehChaves commented on ulift-web/src/index.js
> +serviceWorker.unregister();
Remover linha

2020-03-08 13:38 UTC, GuilhermehChaves commented on ulift-web/src/index.js
> +import './index.css';
Remover linha, não irá precisar desse index.css

2020-03-08 13:38 UTC, GuilhermehChaves commented on ulift-web/src/App.js
> +import logo from './logo.svg';
Remover linha

2020-03-08 13:38 UTC, GuilhermehChaves commented on ulift-web/src/App.js
> +        <img src={logo} className="App-logo" alt="logo" />
Remover linha, não iremos precisa da logo

2020-03-10 16:03 UTC, GuilhermehChaves approved these changes

2020-03-11 02:22 UTC, grabsks approved these changes

2020-03-11 02:22 UTC, merged