Criação tela de login
grabsks/uLift pull request #25
Opened 2020-03-23 22:19 UTC by luanfonsecap

2020-03-24 00:30 UTC, GuilhermehChaves approved these changes

2020-03-27 16:05 UTC, grabsks requested changes

2020-03-27 16:05 UTC, GrabK5 commented on ulift-web/src/Pages/Login/index.js
> +    //send to API
Remover comentário

2020-03-27 16:05 UTC, GrabK5 commented on ulift-web/src/Pages/Login/styles.css
> +
Remover espaço

2020-03-27 16:27 UTC, Hermes-Francisco approved these changes

2020-03-27 16:37 UTC, Hermes-Francisco approved these changes

2020-03-27 16:39 UTC, Hermes-Francisco approved these changes

2020-03-27 16:43 UTC, grabsks approved these changes

2020-03-27 16:44 UTC, merged