WIP: 4 implementa landing page
grabsks/uLift pull request #35
Opened 2020-03-30 21:31 UTC by GrabK5

2020-04-02 23:51 UTC, luanfonsecap requested changes

2020-04-02 23:51 UTC, luanfonsecap commented on ulift-web/src/Pages/LandingPage/index.js
> +function App() {
troca o nome da função pra Landing Page

2020-04-02 23:51 UTC, luanfonsecap commented on ulift-web/src/Pages/LandingPage/index.js
> +export default App;
Troca o nome da exportação para Landing Page

2020-04-02 23:51 UTC, luanfonsecap commented on ulift-web/src/routes.js
> +import App from "./Pages/LandingPage/index";
Troca a importação  para LandingPage também

2020-05-26 22:31 UTC, luanfonsecap approved these changes

2020-05-26 23:29 UTC, GrabK5 commented on ulift-web/src/Pages/LandingPage/index.js
> +function App() {
resolvido

2020-05-26 23:37 UTC, GuilhermehChaves approved these changes

2020-05-26 23:41 UTC, merged